import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { Grid, Paper, styled } from "@mui/material";
import TaskForm from "./components/TaskForm";
import TaskList from "./components/TaskList";
import { Task } from "./interfaces/Task";
import { useState } from "react";


const inter = Inter({ subsets: ["latin"] });

const Item = styled(Paper)(({ theme }) => ({
  backgroundColor: theme.palette.mode === "dark" ? "#1A2027" : "#fff",
  ...theme.typography.body2,
  padding: theme.spacing(1),
  textAlign: "center",
  color: theme.palette.text.secondary,
}));

export default function Home() {

  const [taskList, setTaskList] = useState<Task[]>([])     // passa array Task[] vazio

  const deleteTask = ( id:number) => {
    setTaskList(
      taskList.filter( task => {
        return task.id !== id
      })
    )
  }

  return (
    <>
      <Head>
        <title>App Todo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Grid container spacing={2}>
        <Grid item xs={12}>
          <Item sx={{ background: "blue" }}>
            <h2> App todo</h2>
          </Item>
        </Grid>

        <Grid item xs={2}>
          <Item>Espaço sobrando</Item>
        </Grid>
        <Grid item xs={8}>
          <Item>
            <div>
              <h2>o que vc vai fazer </h2>
              <TaskForm  setTaskList={setTaskList} taskList={taskList} btnText="criar tarefa"></TaskForm>
            </div>
            <br></br>
            <div>
              <h2>suas tarefas:</h2>
              <TaskList handleDelete={deleteTask} taskList={taskList}></TaskList>
            </div>
          </Item>
        </Grid>
        <Grid item xs={2}>
          <Item>Espaço sobrando</Item>
        </Grid>

        <Grid item xs={12}>
          <Item sx={{ background: "blue" }}>
            <h2>Footer</h2>
          </Item>
        </Grid>
      </Grid>
    </>
  );
}
